Repository: Products.PlonePAS


Branch: refs/heads/5.x
Date: 2019-01-16T10:29:58+01:00
Author: Andreas Jung (zopyx) <info@zopyx.com>
Commit: https://github.com/plone/Products.PlonePAS/commit/c67891510cbb80a4936936b77db5672e6044a27f

fixed old-style exception

Files changed:
A news/44.fixed
M src/Products/PlonePAS/tools/groupdata.py

b'diff --git a/news/44.fixed b/news/44.fixed\nnew file mode 100644\nindex 0000000..dfb0a28\n--- /dev/null\n+++ b/news/44.fixed\n@@ -0,0 +1 @@\n+old-style exception fixed in groupdata.py\ndiff --git a/src/Products/PlonePAS/tools/groupdata.py b/src/Products/PlonePAS/tools/groupdata.py\nindex a7b74e6..c0e1485 100644\n--- a/src/Products/PlonePAS/tools/groupdata.py\n+++ b/src/Products/PlonePAS/tools/groupdata.py\n@@ -35,6 +35,10 @@\n _marker = object()\n \n \n+class GroupDataError(Exception):\n+    pass\n+\n+\n @implementer(IGroupDataTool)\n class GroupDataTool(UniqueObject, SimpleItem, PropertyManager):\n     """This tool wraps group objects, allowing transparent access to\n@@ -132,7 +136,7 @@ def getGroup(self):\n         bcontext = aq_base(parent)\n         bcontainer = aq_base(aq_parent(aq_inner(self)))\n         if bcontext is bcontainer or not hasattr(bcontext, \'getUserName\'):\n-            raise \'GroupDataError\', "Can\'t find group data"\n+            raise GroupDataError("Can\'t find group data")\n         # Return the user object, which is our context.\n         return parent\n \n'

